server:
  port: 9003

brokers: localhost:9092

spring:
  profiles:
    active: dev
  security:
    jwt:
      secret: my-super-secret-key-my-super-secret-key
  data:
    redis:
      host: localhost
      port: 6379
      password: MyStrongPassword
  datasource:
    url: jdbc:mysql://localhost:3307/mydatabase
    username: user
    password: mypass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    username: atulrathodc@gmail.com
    password: "fvpm xuzo kdyu wldi"
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    cache: false
    charset: UTF-8
    expose-spring-macro-helpers: true
  main:
    web-application-type: reactive
    allow-circular-references: true
    allow-bean-definition-overriding: true
  cloud:
    vault:
      uri: http://127.0.0.1:8200
      kv:
        enabled: false
        backend: secret
        default-context: example
    gateway:
      routes:
        - id: inventory-service
          uri: http://localhost:9004
          predicates:
            - Path=/inventory/**
          filters:
            - StripPrefix=1   # removes /inventory before forwarding

        - id: product-service
          uri: http://localhost:9006
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1   # removes /order before forwarding

        - id: payment-service
          uri: http://localhost:9005
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=1   # removes /payment before forwarding
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE

logging:
  level:
    org:
      springframework:
        security: DEBUG
    org.apache.kafka.clients.NetworkClient: ERROR
    org.apache.kafka.clients.producer.ProducerConfig: ERROR
    org.apache.kafka.clients.consumer.ConsumerConfig: ERROR
    org.apache.kafka.clients: ERROR

support:
  email: atulrathodc@gmail.com
  name: Atul Rathod

stripe:
  secret:
    key: sk_test_XXXXXXXXXXXXXXXXXXXX

openai:
  model: gpt-4o-mini
  api:
    key: sk-svcacct-IV3H3npvGdyco2RPOQD2jLZx4vtPSDenb-nSoHeBCCrzSyHA1pS3Loi-gKowfOT3BlbkFJHIW8ui5Y43Xz_iU3gO7vI5XnSH4PMrlO-8uX9DIUDtUC2LpRTO532KeVyitQMA
    url: https://api.openai.com/v1/chat/completions

my:
  framework:
    enabled: true
    apiKey: abc-123-secret

management:
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      base-path: /actuator

resilience4j:
  circuitbreaker:
    instances:
      myService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 50s
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      myService:
        maxAttempts: 3
        waitDuration: 2s
custom:
  property1: value updated
