custom:
  property1: dev
spring:
  cloud:
    vault:
      uri: http://127.0.0.1:8200
      kv:
        enabled: true
        backend: secret
        default-context: example
my:
  db:
    username: "${vault:my-db#username3}"
    password: "${vault:my-db#password}"
